### ISSUE TITLE
1.19.5 regression

### ISSUE THREAD

**Issue by Chippiewill** [nginxinc/docker-nginx-unprivileged#56] opened 2020-12-03 12:52 UTC
@alessfg 

The 1.19.5 release just made seems to have broken the entrypoint:

```
$ docker run -it --rm nginxinc/nginx-unprivileged:1.19.5
Unable to find image 'nginxinc/nginx-unprivileged:1.19.5' locally
1.19.5: Pulling from nginxinc/nginx-unprivileged
Digest: sha256:ed0c9fcace3f7fe25542d5e472fe6d853f3523a6d3362849653cf262ce5ff02a
Status: Downloaded newer image for nginxinc/nginx-unprivileged:1.19.5
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "/docker-entrypoint.sh": permission denied: unknown.
```

Caught this because our CI/CD pipelines are only pinned to 1.19

**Comment by Vovcharaa** [comment] 2020-12-03 12:56
Same on stable-alpine

**Comment by rkeck** [comment] 2020-12-03 13:05
impacts all images built in the last hour

**Comment by lorf** [comment] 2020-12-03 13:25
Same on 1.18.0-alpine

**Comment by philicious** [comment] 2020-12-03 13:47
yep, this is a huge regression, breaking alot of CI/CD in the world most likely

**Comment by rkeck** [comment] 2020-12-03 13:49
The problem seems to be that the `docker-entrypoint.sh` isn't marked executable.  
What amazes me, is that when I do a docker build on my local machine using the master branch (which I suppose is used in the CI build process that publishes to Docker Hub), the image works flawless and  `docker-entrypoint.sh` and the scripts inside  `docker-entrypoint.d` are executable.

**Comment by m-brgs** [comment] 2020-12-03 13:55
1.18.0-alpine should not be updated or at least shoudn't reach dockerhub without proper testing -> please find another way to tag your images in order to have stable releases.. or test 🙏

**Comment by rkeck** [comment] 2020-12-03 14:06
Added a workaround (maybe fix) for now.
@ #57

**Comment by philicious** [comment] 2020-12-03 14:06
`1.19.4-alpine` worked for me as quick-fix

**Comment by stephenmoloney** [comment] 2020-12-03 14:08
I would recommend putting some very simple CI in place to validate the images after the build step but before the push step to the container registry.

Eg. After build:

    docker run \
      --rm \
      "nginx:nginx-unprivleged:1.18.0" /bin/bash -c 'echo "build ok"'

If it fails, block the merge request.

**Comment by alexzimmer96** [comment] 2020-12-03 14:16
This just broke our CI/CD-systems. Can someone say how long it'll take to fix this?

**Comment by alessfg** [comment] 2020-12-03 14:49
Hey all! I'm tremendously sorry this happened! I'm pushing a fix right now, should hopefully be solved within the next half hour.

**Comment by jmcshane** [comment] 2020-12-03 14:52
Can I ask why it was pushed to the previous tag versions?  Our dockerfile references `nginxinc/nginx-unprivileged:1.18-alpine`, why was that tag referenced as well as 1.19 as this PR seems intended for 1.19?

**Comment by alessfg** [comment] 2020-12-03 14:54
> Can I ask why it was pushed to the previous tag versions? Our dockerfile references `nginxinc/nginx-unprivileged:1.18-alpine`, why was that tag referenced as well as 1.19 as this PR seems intended for 1.19?

There's some changes across all images (eg, the stopsignal has finally changed to `sigquit`).

**Comment by alessfg** [comment] 2020-12-03 14:56
> I would recommend putting some very simple CI in place to validate the images after the build step but before the push step to the container registry.
> 
> Eg. After build:
> 
> ```shell
> docker run \
>   --rm \
>   "nginx:nginx-unprivleged:1.18.0" /bin/bash -c 'echo "build ok"'
> ```
> 
> If it fails, block the merge request.

This is one of those things that's been in the roadmap forever, but I haven't had the time to prioritize. I might try to check out GH actions sometimes soonish though.

**Comment by jmcshane** [comment] 2020-12-03 14:56
ah, makes sense @alessfg, i guess we'll pin on patch versions now instead of minor.

appreciate your quick step up on these issues, thank you

**Comment by alessfg** [comment] 2020-12-03 14:58
Aight, new images should be live now. Can you all check and see if your builds are working?

**Comment by stephenmoloney** [comment] 2020-12-03 14:58
> This is one of those things that's been in the roadmap forever, but I haven't had the time to prioritize. I might try to check out GH actions sometimes soonish though.

Totally understand. 

I always appreciate people's effort on opensource.

Time is limited.

**Comment by jmcshane** [comment] 2020-12-03 15:07
Working for me. @alessfg shout out for the fast resolution. I appreciate any work in open source, and getting resolution like this shows incredible dedication to the community

**Comment by alessfg** [comment] 2020-12-03 15:27
Cool, closing this then.

**Closed by alessfg** 2020-12-03 15:27 UTC

**Comment by stephenmoloney** [comment] 2020-12-03 16:54
Problems solved on my side too.
